version: 2

jobs:
  build:
    working_directory: ~/knotweed
    docker:
      - image: circleci/ruby:2.5.3-node
        environment:
          BUNDLE_PATH: vendor/bundle
          PGUSER: knotweed
          RAILS_ENV: test
          DATABASE_URL: postgres://localhost/subtext_test_db?pool=5&encoding=unicode
          TZ: "/usr/share/zoneinfo/America/New_York"
      - image: circleci/postgres:9.5
        environment:
          POSTGRES_USER: knotweed
          POSTGRES_PASSWORD: ""
      - image: elasticsearch:6.5.4
      - image: circleci/redis
    steps:
      - checkout

      - restore_cache:
          keys:
            - knotweed-bundle-{{ checksum "Gemfile.lock" }}
            - knotweed-bundle-

      - run:
          name: bundle check & install
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3

      - save_cache:
          key: knotweed-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Database setup
          command: |
            bundle exec rake db:create
            bundle exec rake db:schema:load

      - run: mkdir ~/rspec
      - run:
          name: Run tests
          command: bundle exec rspec --format progress --format RspecJunitFormatter -o ~/rspec/rspec.xml
          when: always
      - store_test_results:
          path: ~/rspec
      - store_artifacts:
          path: ~/knotweed/coverage
          destination: ~/coverage
