#!/bin/bash

map_file="/etc/nginx/blogger.redirects"
lock_file="/var/update_nginx_rewrites.lock"
last_updated_at_cache_file="/var/update_nginx_rewrites.sh_last_updated_at"
export PGPASSWORD=$RAILS_KNOTWEED_DB_PASSWORD

if [ ! -e "$map_file" ]; then
    touch "$map_file"
fi

if [ -e $lock_file ]
then
    echo "looks like this process is already running; if this takes more than 1 minute, we may need to reconsider the way we do these redirects"
    exit 1
fi
touch $lock_file

rewrite_host=$CONSUMER_APP_URI

if [ ! -e $map_file ]
then
    # if the map file doesn't exist we start from scratch
    rm $last_updated_at_cache_file
fi
last_updated_at="0000-00-00 00:00:00"
if [ -e $last_updated_at_cache_file ]
then
    last_updated_at=`cat $last_updated_at_cache_file`
fi

something_updated=$(/usr/bin/psql -tA -U $RAILS_KNOTWEED_DB_USERNAME -h $RAILS_KNOTWEED_DB_HOST $RAILS_KNOTWEED_DB_NAME -c "SELECT count(1) FROM rewrites WHERE updated_at>'$last_updated_at'")
if [ "$something_updated" != "0" ]
then
    /usr/bin/psql -tA -U $RAILS_KNOTWEED_DB_USERNAME -h $RAILS_KNOTWEED_DB_HOST $RAILS_KNOTWEED_DB_NAME -c "select 'location ~* /' || source || E' {\n    add_header Cache-Control no-store;\n    rewrite ^ $rewrite_host/' || destination || E' permanent;\n}' from rewrites;" > "$map_file"
    date -u +'%F %T' > $last_updated_at_cache_file
fi

rm $lock_file
exit 0
