schedule_listserv_digests:
  cron: "0 0 * * *"
  class: 'ScheduleListservDigestsJob'
  description: "Schedule Listserv Digests for the day."
market_category_count:
  cron: "0 0 * * *"
  class: 'UpdateMarketCategoriesCountJob'
  description: "Update result count for market category search results"
remove_expired_tokens:
  cron: "0 0 * * 0"
  class: 'RemoveExpiredTokens'
  description: "Remove expired tokens"
register_temp_users:
  cron: "0 0 * * *"
  class: 'RegisterTempUsersJob'
  description: 'Registers users captures in TempUserCapture table'
