schedule_listserv_digests:
  cron: "0 0 * * *"
  class: 'ScheduleListservDigestsJob'
  description: "Schedule Listserv Digests for the day."
remove_expired_tokens:
  cron: "0 0 * * 0"
  class: 'RemoveExpiredTokens'
  description: "Remove expired tokens"
make_sunsetted_content_private:
  cron: "1 0 * * *"
  class: 'MakeSunsettedContentPrivate'
  description: 'Make sunsetted Content private'
update_promotion_metrics:
  cron: "0 0,12 * * *"
  class: 'SchedulePromotionMetricsUpdateJob'
  description: 'Fetch and persist mailchimp promotion metrics at 12:00AM/12:00PM daily'
