class RemoveUnusedModels < ActiveRecord::Migration
  def up
    drop_table :triples
    drop_table :front_end_builds_apps
    drop_table :front_end_builds_builds
    drop_table :front_end_builds_pubkeys
  end

  def down
    # NOTE: this migration is not fully reversible.
    # the front_end_builds tables are generated by migrations that FEB
    # can create. We don't even have front_end_builds installed in this app,
    # so I'm not supporting reinstating those tables.
    create_table :triples do |t|
      t.integer :dataset_id
      t.string :resource_class
      t.integer :resource_id
      t.string :resource_text
      t.string :predicate
      t.string :object_type
      t.string :object_class
      t.integer :object_resource_id
      t.string :object_resource_text
      t.string :realm
      t.timestamps
  end
end
