PREFIX pub: <http://ontology.ontotext.com/publishing#>
PREFIX luc4: <http://www.ontotext.com/owlim/lucene4#>

SELECT ?uid ?title ?score WHERE {
    ?uid luc4:promoSimilarityIndex """%{content}""" .
    ?uid luc4:score ?score .
    ?uid pub:title ?title .
    ?uid pub:Feature ?feature .
    ?feature pub:featureName "HAS_ACTIVE_PROMOTION" .
    ?feature pub:featureValue "1" .
    FILTER(?uid != <http://www.subtext.org/Document/%{content_id}>) .
} LIMIT 1
