PREFIX pub: <http://ontology.ontotext.com/publishing#>
PREFIX subtext:<http://www.subtext.org/content-attributes#>

SELECT ?uid ?title ?score WHERE {
    ?uid pub:title ?title .
    ?uid subtext:hasActivePromo true .
    ?uid subtext:hasPaidPromo true .
    FILTER(?uid != <http://www.subtext.org/Document/%{content_id}>) .
} ORDER BY RAND() LIMIT 1
